export const LoadingEvents = {
  ADD_PR: 'ADD_PR',
  FETCH_PR_BY_ID: 'FETCH_PR_BY_ID',
  FETCH_PRS: 'FETCH_PRS',
  FETCH_OWN_PRS: 'FETCH_OWN_PRS',
  FETCH_TARGETROLE: 'FETCH_TARGETROLE',
  LOGIN: 'LOGIN',
  FETCH_MEETING: 'FETCH_MEETING',
  FETCH_EMPLOYEES: 'FETCH_EMPLOYEES',
  FILTER_POSSIBILITIES: 'FILTER_POSSIBILITIES',
  DOWNLOAD_FILES: 'DOWNLOAD_FILES',
  UPLOAD_FILES: 'UPLOAD_FILES'
};
