version: "3.7"
services:
  sc_frontend:
    image: pierrezemb/gostatic
    ports: ["${FRONTEND_PORT}:${FRONTEND_PORT}"]
    container_name: ${FRONTEND_CONTAINER_NAME}
    command: "-fallback index.html"
    volumes:
      - ./build:/srv/http
